# Generated by Django 3.2.3 on 2022-11-11 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='카테고리이름')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('report_count', models.IntegerField(verbose_name='신고수')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='노출 제한')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member', verbose_name='작성자')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.post', verbose_name='원본글')),
            ],
        ),
    ]
