# Generated by Django 3.2.3 on 2022-11-11 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20221111_1708'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('subtitle', models.CharField(max_length=255, verbose_name='부제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제된 글')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.category', verbose_name='카테고리')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member', verbose_name='작성자')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='원본글'),
        ),
    ]
