# Generated by Django 3.2.3 on 2022-11-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20221111_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제일'),
        ),
    ]
