# Generated by Django 3.2.3 on 2022-11-11 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='member',
        ),
    ]
