# Generated by Django 3.2.3 on 2022-11-11 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20221111_1708'),
        ('post', '0002_auto_20221111_1708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
