# Generated by Django 3.2.3 on 2022-11-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_certificated',
            field=models.BooleanField(default=False, verbose_name='인증여부'),
        ),
    ]
